FROM node:latest

WORKDIR /usr/src/app/
COPY app/. /usr/src/app/

RUN npm install --force
RUN npm install -g nodemon

RUN chmod +x /usr/src/app/update.sh

RUN curl -fsSL https://get.docker.com -o get-docker.sh; sh get-docker.sh

RUN apt install -f git
RUN git config --global --add safe.directory /dockerProject

ENTRYPOINT nodemon index.js
